print("What is your name?")
name = input(Eldar)
print("How old are you?")
age = input(21)
print("Where are you live?")
city = input(Stavropol)
print("This is", name)
print("It is", age)
print("S(he) live in", city)