print("What is your name?")
name = input()
print("How old are you?")
age = input()
print("Where are you live?")
city = input()
print("This is", name)
print("It is", age)
print("S(he) live in", city)